### ISSUE TITLE
Apothic Attributes 1.20.1-1.3.1 gets detected as a malicious file by Windows Defender

### ISSUE THREAD

**Issue by Boo566ya8** [Shadows-of-Fire/Apothic-Attributes#21]
Version 1.20.1-1.3.1 of Apothic Attributes gets automatically deleted by Windows Defender when starting Minecraft, causing a crash. This is not the case with the previous version (1.20.1-1.3.0).

**Comment by Shadows-of-Fire** [comment]
VirusTotal doesn't report and issues with the jar: https://www.virustotal.com/gui/file/cd3cd0fca94d9f529fa405d57cd88047b10fd16028ccb04870b684bc72bbd675?nocache=1

I'm starting to think defender is being overzealous with unknown jar files or something, since this also happened with the latest apoth release: https://github.com/Shadows-of-Fire/Apotheosis/issues/1198

**Comment by Boo566ya8** [comment]
That's odd, I don't have any issue with the latest release of Apotheosis.
