### ISSUE TITLE
Little Tooltip incompatibility with Quality Equipment

### ISSUE THREAD

**Issue by Kanekami** [Shadows-of-Fire/Apothic-Attributes#30]
When reforging equipment the attribute modifiers from the quality are merged with the default attribute modifiers leaving a strange "When in main hand:"

With AttributesLib:
![2024-06-23_12 10 55](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/137314531/a5c2cd6e-e170-4506-b756-bd893d062bfb)
![2024-06-23_12 10 57](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/137314531/4e23e401-65bd-4958-be51-056f269b425d)

Without AttributesLib:
![2024-06-23_12 13 19](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/137314531/c4254b24-5a4d-4b69-ac12-6ce387956195)

Mods
Forge-47.3.0
Quality Equipment 1.3-forge-1.20.1 (Latest)
AttributesLib-1.20.1-1.3.5
Placebo-1.20.1-8.6.2

**Comment by Shadows-of-Fire** [comment]
There isn't much I can do to account for that since tooltip lines are not "owned" and cannot be identified as coming from any one mod.  The best way for this to work nicely would be for Quality Equipment to utilize the apis provided by Apothic Attributes to properly (a) hide the tooltips from the main display and (b) add them after the normal tooltip block.

However, Quality Equipment is a closed source mod, so no further support will be provided here.  You can ask them if they would like to implement such support.  The relevant AA events are `GatherSkippedAttributeTooltipsEvent` and `AddAttributeTooltipsEvent`

**Comment by NerdyPuzzle** [comment]
The quality equipment tooltips gather the text of the modifiers they own from the components, remove the original ones from above and add new literal components with the gathered text (gotten with component.getString)

**Comment by NerdyPuzzle** [comment]
So you could tell the tooltips apart by the lack of a modifier translation key when doing component.toString and not remove them
