### ISSUE TITLE
[1.20.1] Spoorn Attribute mods not showing up on Stats screen. 

### ISSUE THREAD

**Issue by ffuentesm** [Shadows-of-Fire/Apothic-Attributes#7]
The mods by spoorn add a list of attributes to weapons and armor, ranging from extra health, speed boost, life steal, freeze damage, etc. But for some reason, those are not showing up on the stats. 

https://modrinth.com/mod/spoorn-weapon-attributes
https://modrinth.com/mod/spoorn-armor-attributes

![image](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/44974827/686751ae-6d6f-42a9-a421-0324585973ec)
![image](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/44974827/c7db2bc9-fe67-45ad-a16e-41d8061bc977)
![image](https://github.com/Shadows-of-Fire/Apothic-Attributes/assets/44974827/44f70029-941b-4731-8d24-f47c74377fcd)

**Comment by Shadows-of-Fire** [comment]
The linked mods do not use Minecraft's Attribute system at all, and have reinvented another layer of pseudo-attributes on top of everything. There's nothing I can do about it.  

You would need to ask them to rewrite their mod to actually use attributes and attribute modifiers instead of storing everything in a secondary nbt storage and deserializing things on the fly.
